# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  terraform

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t cprimemyacr321012.azurecr.io/web:tag Weather-App-ReactJS-main
      az acr login -n cprimemyacr321012
      docker push cprimemyacr321012.azurecr.io/web:tag
- script: cat k8s-manifest/Deployment.yml
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
    azureResourceGroup: 'cprime_rg'
    kubernetesCluster: 'cprime-cluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'k8s-manifest'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
    azureContainerRegistry: 'cprimemyacr321012.azurecr.io'
    forceUpdate: false