# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: terraform

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build . -t shecloud   
      docker tag shecloud cprimemyacr321012.azurecr.io/shecloud 
      docker run -p 3000:3000  cprimemyacr321012.azurecr.io/shecloud 
      az acr login --name cprimemyacr321012  
      docker images 
      docker push cprimemyacr321012.azurecr.io/shecloud
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
    azureResourceGroup: 'cprime_rg'
    kubernetesCluster: 'cprime-cluster'
    namespace: 'default'
    manifests: 'k8s-manifest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
    azureResourceGroup: 'cprime_rg'
    kubernetesCluster: 'cprime-cluster'
    namespace: 'default'
    command: 'apply'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
    azureContainerRegistry: 'cprimemyacr321012.azurecr.io'