# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  terraform


steps:
- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/bhavi'
    backendServiceArm: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
    backendAzureRmResourceGroupName: 'cprime_rg'
    backendAzureRmStorageAccountName: 'cprimestorageacc017'
    backendAzureRmContainerName: 'cprime-file'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV4@4
  displayName: 'Terraform validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/bhavi'
    environmentServiceNameAzureRM: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/bhavi'
    environmentServiceNameAzureRM: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
- task: TerraformTaskV4@4
  displayName: 'Terraform Deploy'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
- task: TerraformTaskV4@4
  displayName: 'Terraform Destroy'
  inputs:
    provider: 'azurerm'
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/bhavi'
    environmentServiceNameAzureRM: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'
- task: TerraformTaskV4@4
  displayName: 'Terraform Redeploy'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/bhavi'
    environmentServiceNameAzureRM: 'Free Trial(3c850cea-049e-4bff-a039-406dc6fafa3c)'